### ISSUE TITLE
test failures with python 3.12

### ISSUE THREAD

**Issue by ncopa** [kalekundert/pytest_tmp_files#5]
When upgrading python to 3.12 on Alpine Linux I bumped into this error in test:

```
======================================= test session starts ========================================
platform linux -- Python 3.12.3, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/ncopa/aports/community/py3-pytest-tmp-files/src/pytest_tmp_files-0.0.2
configfile: pyproject.toml                                                                          
plugins: pytest_tmp_files-0.0.2      
collected 23 items                                                                                 
                                                                                                    
pytest_tmp_files/make.py ..                                                                  [  8%] 
tests/test_make.py ..........F........                                                       [ 91%]
tests/test_plugin.py ..                                                                      [100%]
                                                                                                    
============================================= FAILURES =============================================
__________________________________________ test_make_fifo __________________________________________
                                                  
cls = <class '_pytest.runner.CallInfo'>                                                             
func = <function call_and_report.<locals>.<lambda> at 0x7fbd395d8400>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)               
                                                  
    @classmethod                                                                                    
    def from_call(                                                                                  
        cls,                                                                                        
        func: Callable[[], TResult],                                                                
        when: Literal["collect", "setup", "call", "teardown"],
        reraise: Optional[                                                                          
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,                                                                                   
    ) -> "CallInfo[TResult]":                                                                       
        """Call func, wrapping the result in a CallInfo.
                                                                                                    
        :param func:                              
            The function to call. Called without arguments.
        :param when:                                                                                
            The phase in which the function is called.
        :param reraise:                           
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """                                       
        excinfo = None                            
        start = timing.time()            
        precise_start = timing.perf_counter()
        try:                                                                                        
>           result: Optional[TResult] = func()

/usr/lib/python3.12/site-packages/_pytest/runner.py:340: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.12/site-packages/_pytest/runner.py:240: in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
/usr/lib/python3.12/site-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/usr/lib/python3.12/site-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3.12/site-packages/_pytest/threadexception.py:87: in pytest_runtest_call
    yield from thread_exception_runtest_hook()
/usr/lib/python3.12/site-packages/_pytest/threadexception.py:63: in thread_exception_runtest_hook
    yield                                         
/usr/lib/python3.12/site-packages/_pytest/unraisableexception.py:90: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook() 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
                                                  
    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            try:                                  
                yield                             
            finally:                              
                if cm.unraisable:                                                                   
                    if cm.unraisable.err_msg is not None:
                        err_msg = cm.unraisable.err_msg
                    else:                
                        err_msg = "Exception ignored in"
                    msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                    msg += "".join(        
                        traceback.format_exception(
                            cm.unraisable.exc_type,
                            cm.unraisable.exc_value,
                            cm.unraisable.exc_traceback,
                        )            
                    )                             
>                   warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E                   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [clos
ed]>                                              
E                                                 
E                   Traceback (most recent call last):
E                     File "/usr/lib/python3.12/pathlib.py", line 555, in drive
E                       return self._drv
E                              ^^^^^^^^^
E                   AttributeError: 'PosixPath' object has no attribute '_drv'
E                                                 
E                   During handling of the above exception, another exception occurred:
E                                                 
E                   Traceback (most recent call last):
E                     File "<frozen posixpath>", line 82, in join
E                   ResourceWarning: unclosed file <_io.FileIO name='demo.xlsx' mode='rb' closefd=Tr
ue>                                                                                                 
                                                  
/usr/lib/python3.12/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarnin
g                                                 
===================================== short test summary info ======================================
FAILED tests/test_make.py::test_make_fifo - pytest.PytestUnraisableExceptionWarning: Exception ignor
ed in: <_io.FileIO [closed]>       
=================================== 1 failed, 22 passed in 0.24s ===================================
```

If I disbale that test, it will fail on next.

Not sure how to debug this?

**Comment by kalekundert** [comment]
Wow, that's really weird.  I've never seen an error like that before.  I suspect that the problem might be similar to what's described in [this article](https://medium.com/@BartekSkwira/how-to-solve-pytest-pytestunraisableexceptionwarning-8d75a4d1f801), i.e. that an error is occurring when some resource is being destructed.  It's notable that the error message mentions `'demo.xlsx'`.  This is a file that's used in one of the doctests from `pytest_tmp_files/make.py`, so it has nothing to do with the test that's failing.  I confirmed that this file does in fact get closed.  Specifically, the test calls `openpyxl.load_workbook()`, and this function both opens and closes the file in question.  But the error seems to indicate that it's still open somehow...

For what's it's worth, I also took a look at line 555 of `pathlib.py` (for python 3.12.3), which is the source of the `'PosixPath' object has no attribute '_drv'` exception.  This line is contained in a try/catch block meant to handle this exact exception, so there's nothing unusual going on here. I suspect that the "unraisable exception" is triggered by a garbage-collection step, and it's just a coincidence that such a step happens while this exception is being handled.

It's also worth mentioning that I can't reproduce this error in my normal dev environment (python 3.12.1, Arch).  But I haven't tried making an Alpine container.

The article I linked above mentions that this error can be ignored with:
```
pytest --disable-warnings
```
If that works for you, it might be the best approach.  For one thing, I don't think there's anything wrong with the code itself.  I suspect the problem is related to the `demo.xlsx` file not being cleaned up properly, and it's just a documentation example anyways. For another, after looking into this for an hour or so, I don't think I'll be able to make a proper fix quickly (or possibly at all).  That said, I know it's bad to ignore warnings, so I'll try to keep poking at this.
